(function(root){
  'use strict';
  const D=root.ArenaData||(typeof require!=='undefined'?require('./data.js'):null);
  const copy=x=>JSON.parse(JSON.stringify(x));
  function random(s){let t=s.seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);s.seed=s.seed>>>0;return ((t^t>>>14)>>>0)/4294967296;}
  const pick=(s,a)=>a[Math.floor(random(s)*a.length)];
  function createUnit(s,id,star=1){return {uid:s.uid++,id,star,items:[]};}
  function createPlayer(id,name,style){return {id,name,style,hp:100,gold:0,level:1,xp:0,board:Array(28).fill(null),bench:Array(9).fill(null),shop:Array(5).fill(null),locked:false,streak:0,last:null,wins:0,augments:[],inventory:[],outRound:null};}
  function newGame(seed=Date.now()>>>0){
    const s={version:8,seed,uid:1,round:1,phase:'prep',difficulty:'normal',pool:Object.fromEntries(Object.values(D.units).map(d=>[d.id,D.poolSizes[d.cost]])),players:[],logs:[],reward:null,rank:null,lastResult:null,pendingLoot:[],legend:{id:'bitmon',x:50,y:88}};
    const names=['나의 테이머','태일 · 용의 용기','매튜 · 푸른 송곳니','소라 · 불꽃 날개','미나 · 초록 정원','리키 · 빛의 수호자','한솔 · 전자 폭풍','나리 · 성스러운 빛'];
    const styles=['용형','용형','야수형','조류형','식물형','천사형','곤충형','백신'];
    s.players=names.map((n,i)=>createPlayer(i,n,styles[i]));
    s.players.forEach((p,i)=>{const id=i===0?'koromon':pick(s,['koromon','tsunomon','mochimon','tanemon','pyocomon','tokomon']);s.pool[id]--;p.board[3]=createUnit(s,id);roll(s,p,true);});
    log(s,'파일 아일랜드에 접속했습니다. 상대를 정찰하고 팀을 준비하세요.');return s;
  }
  function log(s,text){s.logs.unshift(text);s.logs=s.logs.slice(0,60);}
  function returnShop(s,p){p.shop.forEach(id=>{if(id)s.pool[id]++;});p.shop.fill(null);}
  function hasThreeStar(p,id){return all(p).some(u=>u.id===id&&u.star===3);}
  function draw(s,p){const odds=D.odds[p.level];let r=random(s)*100,cost=1;for(let i=0;i<5;i++){r-=odds[i];if(r<0){cost=i+1;break;}}const eligible=Object.values(D.units).filter(d=>d.cost===cost&&s.pool[d.id]>0&&!hasThreeStar(p,d.id));const total=eligible.reduce((n,d)=>n+s.pool[d.id],0);if(!total)return null;let n=random(s)*total;for(const d of eligible){n-=s.pool[d.id];if(n<0){s.pool[d.id]--;return d.id;}}return null;}
  function roll(s,p,free=false){if(!['prep','battle'].includes(s.phase)||s.reward||(!free&&p.gold<2))return false;if(!free)p.gold-=2;returnShop(s,p);p.shop=Array.from({length:5},()=>draw(s,p));return true;}
  function all(p){return [...p.board,...p.bench].filter(Boolean);}
  function combine(s,p){let changed=true;while(changed){changed=false;for(const d of Object.values(D.units)){for(let star=1;star<3;star++){let refs=[];['board','bench'].forEach(area=>p[area].forEach((u,i)=>{if(u&&u.id===d.id&&u.star===star)refs.push({area,i,u});}));if(refs.length<3)continue;const chosen=refs.slice(0,3),keep=chosen[0];const items=chosen.flatMap(r=>r.u.items);chosen.forEach(r=>p[r.area][r.i]=null);keep.u.star++;keep.u.items=items.slice(0,2);p.inventory.push(...items.slice(2));p[keep.area][keep.i]=keep.u;if(keep.u.star===3)p.shop=p.shop.map(id=>{if(id!==d.id)return id;s.pool[id]++;return null;});changed=true;if(p.id===0)log(s,`${d.name} ${star+1}성 합성!`);}}}}
  function buy(s,p,index){if(!['prep','battle'].includes(s.phase)||s.reward)return false;const id=p.shop[index],d=D.units[id];if(!d||p.gold<d.cost)return false;let slot=p.bench.indexOf(null);if(slot<0){const pair=all(p).filter(u=>u.id===id&&u.star===1);if(pair.length<2)return false;slot=p.bench.length;}p.gold-=d.cost;p.shop[index]=null;p.bench[slot]=createUnit(s,id);combine(s,p);p.bench=p.bench.slice(0,9);return true;}
  function sell(s,p,area,index){const u=p[area]?.[index];if(!['prep','battle'].includes(s.phase)||(s.phase==='battle'&&area!=='bench')||s.reward||!u)return false;p.gold+=D.units[u.id].cost*Math.pow(3,u.star-1);s.pool[u.id]+=Math.pow(3,u.star-1);p.inventory.push(...u.items);p[area][index]=null;return true;}
  function move(s,p,from,fi,to,ti){if(!['prep','battle'].includes(s.phase)||(s.phase==='battle'&&(from==='board'||to==='board'))||s.reward||!['board','bench'].includes(from)||!['board','bench'].includes(to)||!Number.isInteger(fi)||!Number.isInteger(ti)||fi<0||ti<0||fi>=p[from].length||ti>=p[to].length||!p[from][fi])return false;const a=p[from][fi],b=p[to][ti];const delta=(to==='board'?1:0)-(from==='board'?1:0);if(delta>0&&!b&&p.board.filter(Boolean).length>=p.level)return false;[p[from][fi],p[to][ti]]=[b,a];return true;}
  function addXp(p,n){p.xp+=n;while(p.level<9&&p.xp>=D.xp[p.level]){p.xp-=D.xp[p.level];p.level++;}if(p.level===9)p.xp=0;}
  function buyXp(s,p){if(!['prep','battle'].includes(s.phase)||s.reward||p.level>=9||p.gold<4)return false;p.gold-=4;addXp(p,4);return true;}
  function recipeFor(a,b){if(D.items[a]?.kind!=='component'||D.items[b]?.kind!=='component')return null;return D.completedItems.find(id=>{const r=D.items[id].recipe;return (r[0]===a&&r[1]===b)||(r[1]===a&&r[0]===b);})||null;}
  function canCraft(p,id){const recipe=D.items[id]?.recipe;if(!recipe)return false;const needed={};recipe.forEach(part=>needed[part]=(needed[part]||0)+1);return Object.entries(needed).every(([part,n])=>p.inventory.filter(x=>x===part).length>=n);}
  function craft(s,p,id){if(!['prep','battle'].includes(s.phase)||s.reward||!canCraft(p,id))return false;for(const part of D.items[id].recipe)p.inventory.splice(p.inventory.indexOf(part),1);p.inventory.push(id);if(p.id===0)log(s,D.items[id].name+' 합성 완료');return true;}
  function equip(s,p,uid,index){const u=all(p).find(x=>x.uid===uid),id=p.inventory[index];if(!['prep','battle'].includes(s.phase)||s.reward||!u||!D.items[id]||!Number.isInteger(index)||index<0)return false;
    const partner=D.items[id].kind==='component'?u.items.findIndex(x=>D.items[x].kind==='component'):-1;
    if(partner>=0){const result=recipeFor(u.items[partner],id);if(!result)return false;u.items[partner]=result;p.inventory.splice(index,1);if(p.id===0)log(s,D.items[result].name+' 장착 합성');return true;}
    if(u.items.length>=2)return false;u.items.push(p.inventory.splice(index,1)[0]);return true;}
  function unequip(s,p,uid,index){const u=all(p).find(x=>x.uid===uid);if(!['prep','battle'].includes(s.phase)||s.reward||!u||!u.items[index])return false;p.inventory.push(u.items.splice(index,1)[0]);return true;}
  function traits(units){const counts={};new Set(units.map(u=>u.id)).forEach(id=>{const d=D.units[id];[d.attr,d.family].forEach(t=>counts[t]=(counts[t]||0)+1);});return Object.entries(D.traits).map(([name,d])=>{const count=counts[name]||0,tier=d.cuts.filter(n=>count>=n).length;return {name,count,tier,cuts:d.cuts,description:tier?d.text[tier-1]:d.text[0]};});}
  function aiTurn(s,p){if(p.hp<=0||s.phase!=='prep')return;const desired=Math.min(9,3+Math.floor(s.round/2));while(p.level<desired&&p.gold>=8)buyXp(s,p);for(let pass=0;pass<3;pass++){for(let i=0;i<5;i++){const d=D.units[p.shop[i]];if(!d)continue;const matching=all(p).filter(u=>u.id===d.id);if(matching.some(u=>u.star===3))continue;if(all(p).length<p.level+2||d.family===p.style||d.attr===p.style||matching.length){if(p.bench.every(Boolean)&&p.gold>=d.cost){const candidate={id:d.id,star:1,items:[]},weak=p.bench.map((u,i)=>({u,i})).sort((a,b)=>score(a.u,p)-score(b.u,p))[0];if(matching.length>=2||score(candidate,p)>score(weak.u,p))sell(s,p,'bench',weak.i);}buy(s,p,i);}}if(pass<2&&p.gold>12)roll(s,p);else break;}
    const lineup=all(p).sort((a,b)=>score(b,p)-score(a,p));p.board.fill(null);p.bench.fill(null);lineup.forEach((u,i)=>{if(i<p.level){const role=D.units[u.id].role;const choices=(role==='tank'||role==='fighter')?[3,2,4,1,5,0,6,10,9]:[24,22,26,23,25,21,27,17,16];const pos=choices.find(n=>!p.board[n])??p.board.indexOf(null);p.board[pos]=u;}else if(i-p.level<9)p.bench[i-p.level]=u;else{p.gold+=D.units[u.id].cost*3**(u.star-1);s.pool[u.id]+=3**(u.star-1);p.inventory.push(...u.items);}});

    for(let pass=0;pass<10;pass++){const parts=p.inventory.filter(id=>D.items[id].kind==='component');if(parts.length<2)break;craft(s,p,recipeFor(parts[0],parts[1]));}for(const u of p.board.filter(Boolean).sort((a,b)=>score(b,p)-score(a,p))){for(let i=p.inventory.length-1;i>=0;i--)equip(s,p,u.uid,i);}
  }
  function score(u,p){const d=D.units[u.id];return d.cost+u.star*3+(d.family===p.style||d.attr===p.style?1.8:0)+u.items.length;}
  const dist=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);
  const def=id=>D.units[id]||D.creeps[id];
  function makeFighter(u,pos,side,p){const d=def(u.id),scale=[0,1,1.8,3.24][u.star];let c={...copy(u),side,name:d.name,sprite:d.sprite,role:d.role,x:pos%7,y:side===0?4+Math.floor(pos/7):3-Math.floor(pos/7),max:d.hp*scale,hp:0,atk:d.atk*scale,speed:d.speed,range:d.range,armor:d.role==='tank'?35:20,mana:d.role==='mage'?25:0,manaRate:d.role==='mage'?7:d.role==='support'?6:0,crit:0.1,lifesteal:0,regen:0,skillPower:1,healPower:1,startShield:0,shield:0,shieldUntil:0,stun:0,shredUntil:0,cd:0.3,moveCd:0,damage:0,healing:0,casts:0,flash:0};
    for(const item of u.items){const it=D.items[item];c.max+=it.hp||0;c.atk*=1+(it.atk||0);c.armor+=it.armor||0;c.speed*=1+(it.speed||0);c.skillPower+=it.skillPower||0;c.healPower+=it.healPower||0;c.crit+=it.crit||0;c.regen+=it.regen||0;c.startShield+=it.startShield||0;c.manaRate+=it.manaRate||0;c.lifesteal+=it.lifesteal||0;}
    for(const aug of p.augments){if(aug==='fortress')c.max*=1.15;if(aug==='assault'){c.atk*=1.12;c.speed*=1.1;}if(aug==='focus'){c.mana+=15;c.manaRate++;}}
    c.hp=c.max;c.guard=c.max*c.startShield;return c;
  }
  function applyTraits(team){const active=traits(team);for(const t of active){if(!t.tier)continue;for(const u of team){const d=D.units[u.id];if(d.attr!==t.name&&d.family!==t.name)continue;const i=t.tier-1;switch(t.name){case '백신':u.armor+=[12,25,45][i];break;case '데이터':u.speed*=1+[.12,.25,.4][i];break;case '바이러스':u.lifesteal+=[.15,.28][i];break;case '용형':u.atk*=1+[.18,.32][i];break;case '야수형':u.crit+=[.2,.35][i];break;case '곤충형':u.mana=Math.min(100,u.mana+[20,40][i]);break;case '식물형':u.regen+=[.015,.03][i];break;case '천사형':u.guard+=[160,300][i];break;case '조류형':u.skillPower*=[1.2,1.35][i];break;}}}}
  function createBattle(a,b,seed){const units=[];[a,b].forEach((p,side)=>p.board.forEach((u,i)=>{if(u)units.push(makeFighter(u,i,side,p));}));applyTraits(units.filter(u=>u.side===0));applyTraits(units.filter(u=>u.side===1));return {seed,units,time:0,done:false,winner:null,events:[],effects:[],step:0};}
  function event(b,text){b.events.push(text);if(b.events.length>80)b.events.shift();}
  function heal(u,n){if(u.hp<=0)return 0;const actual=Math.max(0,Math.min(n,u.max-u.hp));u.hp+=actual;return actual;}
  function damage(b,a,t,n,magic=false){if(t.hp<=0)return;const armor=t.armor*(t.shredUntil>b.time?.75:1),mitigation=100/(100+armor*(magic?.8:1));let amount=n*mitigation*(b.time>=30?1.65:1);const absorb=Math.min(t.shield,amount);t.shield-=absorb;amount-=absorb;const guardAbsorb=Math.min(t.guard,amount);t.guard-=guardAbsorb;amount-=guardAbsorb;const actual=Math.min(t.hp,amount);t.hp=Math.max(0,t.hp-amount);t.flash=b.time+.18;a.damage+=actual;if(t.role==='tank')t.mana=Math.min(100,t.mana+12);if(a.lifesteal)a.healing+=heal(a,actual*a.lifesteal);}
  function cast(b,u,target){const d=def(u.id),sk=D.skills[d.skill],allies=b.units.filter(v=>v.side===u.side&&v.hp>0),enemies=b.units.filter(v=>v.side!==u.side&&v.hp>0);const power=sk.power*u.atk*u.skillPower;u.mana=0;u.casts++;event(b,`${u.name} · ${sk.name}`);b.effects.push({x:u.x,y:u.y,tx:target.x,ty:target.y,side:u.side,kind:'skill',until:b.time+.5});let targets=[target];
    switch(d.skill){
      case 'blessing':allies.sort((a,b)=>a.hp/a.max-b.hp/b.max).slice(0,3).forEach(v=>u.healing+=heal(v,v.max*.28*u.healPower));targets=enemies.filter(v=>dist(v,target)<=1);break;
      case 'heal':allies.sort((a,b)=>a.hp/a.max-b.hp/b.max).slice(0,2).forEach(v=>u.healing+=heal(v,v.max*.22*u.healPower));return;
      case 'ward':allies.sort((a,b)=>a.hp/a.max-b.hp/b.max).slice(0,3).forEach(v=>{v.shield+=v.max*.22*u.healPower;v.shieldUntil=b.time+5;});return;
      case 'flame':targets=enemies.filter(v=>dist(v,target)<=1);break;
      case 'pierce':target.shredUntil=b.time+5;break;
      case 'shock':targets=enemies.sort((a,b)=>dist(u,a)-dist(u,b)).slice(0,3);targets.forEach(v=>v.stun=b.time+1.2);break;
      case 'thorns':targets=enemies.filter(v=>dist(u,v)<=2);u.shield+=u.max*.18*u.healPower;u.shieldUntil=b.time+5;break;
      case 'rush':break;
      case 'smite':targets=[enemies.sort((a,b)=>a.hp-b.hp)[0]];break;
      case 'missile':{const center=enemies.sort((a,b)=>b.hp-a.hp)[0];targets=enemies.filter(v=>dist(v,center)<=2);break;}
      case 'storm':targets=enemies;targets.forEach(v=>v.stun=b.time+1);break;
      case 'nova':targets=enemies;allies.forEach(v=>u.healing+=heal(v,v.max*.1*u.healPower));break;
    }
    const before=u.damage;targets.forEach(v=>damage(b,u,v,power,true));if(d.skill==='rush')u.healing+=heal(u,(u.damage-before)*.35*u.healPower);
  }
  function walk(b,u,target){const occupied=new Set(b.units.filter(v=>v.hp>0&&v!==u).map(v=>v.y*7+v.x)),start=u.y*7+u.x,queue=[{x:u.x,y:u.y,first:null}],seen=new Set([start]);for(let k=0;k<queue.length;k++){const cur=queue[k];if(cur.first&&dist(cur,target)<=u.range){u.x=cur.first.x;u.y=cur.first.y;return true;}const next=[{x:cur.x+1,y:cur.y},{x:cur.x-1,y:cur.y},{x:cur.x,y:cur.y+1},{x:cur.x,y:cur.y-1}].sort((a,b)=>dist(a,target)-dist(b,target));for(const n of next){const pos=n.y*7+n.x;if(n.x<0||n.x>6||n.y<0||n.y>7||occupied.has(pos)||seen.has(pos))continue;seen.add(pos);queue.push({...n,first:cur.first||n});}}return false;}
  function stepBattle(b,dt=.1){if(b.done)return b;b.time+=dt;b.step++;b.effects=b.effects.filter(e=>e.until>b.time);const order=b.units.filter(u=>u.hp>0);for(let i=order.length-1;i>0;i--){const j=Math.floor(random(b)*(i+1));[order[i],order[j]]=[order[j],order[i]];}
    for(const u of order){if(u.hp<=0)continue;if(u.shieldUntil<=b.time)u.shield=0;u.mana=Math.min(100,u.mana+u.manaRate*dt);if(u.regen)u.healing+=heal(u,u.max*u.regen*dt);if(u.stun>b.time)continue;u.cd-=dt;u.moveCd-=dt;const enemies=b.units.filter(v=>v.side!==u.side&&v.hp>0).sort((a,b)=>dist(u,a)-dist(u,b)||(a.role==='tank'?-1:0)-(b.role==='tank'?-1:0)||a.uid-b.uid);if(!enemies.length)break;const target=enemies[0];if(dist(u,target)>u.range){if(u.moveCd<=0){walk(b,u,target);u.moveCd=.35;}continue;}if(u.mana>=100){cast(b,u,target);u.cd=Math.max(u.cd,.35);}else if(u.cd<=0){const crit=random(b)<u.crit;damage(b,u,target,u.atk*(crit?1.6:1));u.mana=Math.min(100,u.mana+(u.role==='tank'?6:10));u.cd=1/u.speed;b.effects.push({x:u.x,y:u.y,tx:target.x,ty:target.y,side:u.side,kind:crit?'crit':'attack',until:b.time+.22});}}
    const alive=[0,1].map(side=>b.units.some(u=>u.side===side&&u.hp>0));if(!alive[0]||!alive[1]||b.time>=45){b.done=true;b.winner=alive[0]&&!alive[1]?0:alive[1]&&!alive[0]?1:null;}return b;
  }
  function simulate(b){while(!b.done)stepBattle(b);return b;}
  function schedule(s){const ids=s.players.filter(p=>p.hp>0).map(p=>p.id);for(let i=ids.length-1;i>0;i--){const j=Math.floor(random(s)*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]];}const pairs=[];while(ids.length>=2)pairs.push([ids.shift(),ids.shift(),false]);if(ids.length){const ghost=pick(s,s.players.filter(p=>p.id!==ids[0]&&p.hp>0)).id;pairs.push([ids[0],ghost,true]);}return pairs;}
  // The first stage has three encounters; every later stage has seven.
  function roundInfo(s){const n=typeof s==='number'?s:s.round,stage=n<=3?1:2+Math.floor((n-4)/7),step=n<=3?n:1+(n-4)%7;const type=stage===1||step===7?'creep':step===4?'carousel':'pvp';return {stage,step,type,label:`${stage}-${step}`,name:type==='creep'?'야생 디지몬 토벌':type==='carousel'?'디지타마 광장 · 초밥집':'테이머 대전'};}
  function stageDamage(stage,survivors){return Math.ceil((2+(stage-2)*2+survivors)*(1+Math.max(0,stage-2)*.1));}
  function creepTeam(s){const info=roundInfo(s),p=createPlayer(-1,info.stage===1?'악의 숲 · 침입자':`${info.stage}스테이지 · 악당 군단`,'');const starts=[['kuwagamon'],['kuwagamon','shellmon'],['shellmon','devimon']],bosses=[['devimon'],['etemon'],['vamdemon'],['piemon'],['piemon','apocalymon'],['apocalymon'],['apocalymon']],ids=info.stage===1?starts[info.step-1]:bosses[Math.min(bosses.length-1,info.stage-2)],count=info.stage===1?info.step:Math.min(7,info.stage+1);for(let i=0;i<count;i++){const id=ids[i%ids.length];p.board[[3,2,4,10,9,11,17][i]]={uid:-1-i,id,star:1,items:[]};}return p;}
  function grantUnit(s,p,id){if(!id||s.pool[id]<=0)return false;const slot=p.bench.indexOf(null),pair=all(p).filter(u=>u.id===id&&u.star===1).length>=2;if(slot<0&&!pair){p.gold+=D.units[id].cost;return false;}s.pool[id]--;p.bench[slot<0?9:slot]=createUnit(s,id);combine(s,p);p.bench=p.bench.slice(0,9);return true;}
  function rollLoot(s,combat,owner=0){const info=roundInfo(s),kills=combat.units.filter(u=>u.side===1&&u.hp<=0).length,orbs=[];for(let i=0;i<kills;i++){const roll=random(s),drop=roll<.42?null:roll<.72?'common':roll<.92?'blue':'gold';if(!drop)continue;let rewards=drop==='common'?[{kind:'gold',amount:1+Math.floor(random(s)*(info.stage+2))}]:drop==='blue'?[{kind:'item',id:pick(s,D.components)}]:[{kind:'gold',amount:2+info.stage},{kind:random(s)<.55?'unit':'item',id:null}];if(drop==='gold'){const last=rewards[1];if(last.kind==='unit'){const ids=Object.keys(D.units).filter(id=>D.units[id].cost===Math.min(4,Math.max(1,info.stage))&&s.pool[id]>0);last.id=pick(s,ids);if(!last.id)rewards.pop();}else last.id=pick(s,info.stage>=5?D.completedItems:D.components);}orbs.push({id:`${s.round}-${owner}-${i}-${Math.floor(random(s)*1e6)}`,rarity:drop,rewards,x:14+random(s)*72,y:18+random(s)*48});}
    if(info.stage===1&&combat.winner===0&&!orbs.length)orbs.push({id:`${s.round}-${owner}-mercy`,rarity:'common',rewards:[{kind:'gold',amount:1+info.step}],x:25+random(s)*50,y:25+random(s)*35});return orbs;}
  function collectLoot(s,id,playerId=0){const index=s.pendingLoot.findIndex(o=>o.id===id&&o.owner===playerId);if(index<0||(playerId===0&&s.phase!=='prep'))return null;const orb=s.pendingLoot.splice(index,1)[0],p=s.players[playerId],names=[];for(const reward of orb.rewards){if(reward.kind==='gold'){p.gold+=reward.amount;names.push(`${reward.amount}G`);}else if(reward.kind==='item'){p.inventory.push(reward.id);names.push(D.items[reward.id].name);}else if(reward.kind==='unit'&&reward.id){const ok=grantUnit(s,p,reward.id);names.push(ok?D.units[reward.id].name:`${D.units[reward.id].cost}G 전환`);}}if(playerId===0)log(s,`비트몬이 ${orb.rarity==='gold'?'황금':orb.rarity==='blue'?'푸른':'작은'} 전리품 구슬 회수: ${names.join(' / ')}`);return names;}
  function moveLegend(s,x,y){if(!s.legend||s.phase!=='prep')return false;s.legend.x=Math.max(3,Math.min(97,+x||50));s.legend.y=Math.max(3,Math.min(97,+y||88));return true;}
  function setLegend(s,id){if(!D.legends[id]||s.phase==='battle')return false;s.legend={...s.legend,id};return true;}
  function setDifficulty(s,id){if(!D.difficulties[id]||s.phase==='battle')return false;s.difficulty=id;return true;}
  function carouselOptions(s){const cost=Math.min(5,roundInfo(s).stage),ids=shuffle(s,Object.keys(D.units).filter(id=>D.units[id].cost===cost&&s.pool[id]>0)).slice(0,5);return (ids.length?ids:[null,null,null]).map(id=>({unit:id,item:pick(s,roundInfo(s).stage>=5?D.completedItems:D.components)}));}
  function takeCarousel(s,p,option){if(option.unit)grantUnit(s,p,option.unit);else p.gold+=roundInfo(s).stage;p.inventory.push(option.item);}
  function prepareRound(s){if(s.phase!=='prep'||s.reward||s.pairs)return;const info=roundInfo(s);if(info.type==='carousel'){s.reward={type:'carousel',options:carouselOptions(s)};return;}for(const p of s.players.slice(1))aiTurn(s,p);s.pairs=info.type==='pvp'?schedule(s):[];}
  function opponent(s){if(roundInfo(s).type!=='pvp')return -1;const pair=s.pairs?.find(([a,b,g])=>a===0||(!g&&b===0));return pair?(pair[0]===0?pair[1]:pair[0]):1;}
  function startRound(s){if(s.phase!=='prep'||s.reward||roundInfo(s).type==='carousel'||!s.players[0].board.some(Boolean))return null;if(!s.pairs)prepareRound(s);const results=[];let visible=null;const creep=roundInfo(s).type==='creep',difficulty=D.difficulties[s.difficulty]||D.difficulties.normal;const pairs=creep?s.players.filter(p=>p.hp>0).map(p=>[p.id,-1,true]):s.pairs;for(const [a,b,ghost]of pairs){const seed=Math.floor(random(s)*4294967296),own=a===0||(!ghost&&b===0),first=own&&b===0?b:a,second=own&&b===0?a:b,enemy=creep?creepTeam(s):s.players[second];const combat=createBattle(s.players[first],enemy,seed);if(creep){const scale=roundInfo(s).stage===1?.38+.12*roundInfo(s).step:1+.18*(roundInfo(s).stage-2);for(const u of combat.units.filter(u=>u.side===1)){u.max*=scale;u.hp=u.max;u.atk*=scale;}}else if(own&&difficulty.enemyScale!==1){for(const u of combat.units.filter(u=>u.side===1)){u.max*=difficulty.enemyScale;u.hp=u.max;u.atk*=difficulty.enemyScale;}}const r={a:first,b:second,ghost,combat,enemyName:enemy.name};if(own)visible=r;else simulate(combat);results.push(r);}s.phase='battle';return {results,visible};}
  function advanceRound(s){s.round++;s.phase='prep';s.pairs=null;for(const p of s.players.filter(p=>p.hp>0))if(!p.locked)roll(s,p,true);const info=roundInfo(s);if(info.step===1&&[2,3,4].includes(info.stage)){s.reward={type:'augment',options:shuffle(s,Object.keys(D.augments).filter(id=>!s.players[0].augments.includes(id))).slice(0,3)};for(const p of s.players.slice(1).filter(p=>p.hp>0)){const id=pick(s,Object.keys(D.augments).filter(id=>!p.augments.includes(id)));if(id)grantAugment(p,id);}}}
  function finishRound(s,round){if(s.phase!=='battle'||!round?.visible?.combat.done)return false;const info=roundInfo(s),outcomes=new Map();for(const r of round.results){const w=r.combat.winner;const hurt=side=>info.type==='creep'?info.stage+1:stageDamage(info.stage,r.combat.units.filter(u=>u.side!==side&&u.hp>0).reduce((n,u)=>n+u.star,0));outcomes.set(r.a,{win:w===0,draw:w===null,damage:w===0?0:hurt(0)});if(!r.ghost)outcomes.set(r.b,{win:w===1,draw:w===null,damage:w===1?0:hurt(1)});}
    let drops=[];for(const p of s.players){const o=outcomes.get(p.id);if(!o)continue;p.hp=Math.max(0,p.hp-o.damage);if(info.type==='pvp'){const last=o.draw?'draw':o.win?'win':'loss';p.streak=last===p.last?p.streak+1:1;p.last=last;if(o.win)p.wins++;}if(info.type==='creep'&&p.hp>0){const orbs=rollLoot(s,round.results.find(r=>r.a===p.id).combat,p.id).map(orb=>({...orb,owner:p.id}));if(p.id===0){s.pendingLoot.push(...orbs);drops=orbs.map(o=>o.rarity);}else for(const orb of orbs){s.pendingLoot.push(orb);collectLoot(s,orb.id,p.id);}}if(p.hp<=0){p.outRound=s.round;returnShop(s,p);all(p).forEach(u=>s.pool[u.id]+=3**(u.star-1));p.board.fill(null);p.bench.fill(null);}}
    const me=s.players[0],o=outcomes.get(0);s.lastResult={...o,round:info.label,type:info.type,drops,opponent:round.visible.enemyName,stats:round.visible.combat.units.filter(u=>u.side===0).map(u=>({name:u.name,sprite:u.sprite,damage:Math.round(u.damage),healing:Math.round(u.healing),casts:u.casts})).sort((a,b)=>b.damage-a.damage)};log(s,`${info.label} ${info.name} · ${o.draw?'무승부':o.win?'승리':'패배'} · 체력 -${o.damage}`);if(drops.length)log(s,`전리품 구슬 ${drops.length}개가 보드에 떨어졌습니다.`);
    const alive=s.players.filter(p=>p.hp>0);if(me.hp<=0||alive.length===1||s.round>=52){s.rank=me.hp<=0?alive.length+1:[...s.players].sort((a,b)=>b.hp-a.hp||b.wins-a.wins||a.id-b.id).findIndex(p=>p.id===0)+1;s.phase='over';return true;}
    for(const p of alive){const interest=Math.min(5,Math.floor(p.gold/10)),streak=p.last==='draw'?0:p.streak>=5?3:p.streak>=3?2:p.streak>=2?1:0,win=info.type==='pvp'&&outcomes.get(p.id)?.win?1:0,bonus=p.augments.includes('economy')?2:0,base=5+(p.id===0?0:(D.difficulties[s.difficulty]||D.difficulties.normal).aiIncome),total=base+interest+streak+win+bonus;p.gold+=total;addXp(p,2+(p.augments.includes('scholar')?2:0));if(p.id===0)s.income={base,interest,streak,win,bonus,total};}
    advanceRound(s);return true;
  }
  function shuffle(s,a){return a.map(value=>({value,key:random(s)})).sort((a,b)=>a.key-b.key).map(x=>x.value);}
  function grantAugment(p,id){p.augments.push(id);if(id==='economy')p.gold+=5;if(id==='scholar')addXp(p,4);}
  function chooseReward(s,index){if(!s.reward||s.phase!=='prep'||!Number.isInteger(index)||!s.reward.options[index])return false;const reward=s.reward,option=reward.options[index];if(reward.type==='carousel'){takeCarousel(s,s.players[0],option);log(s,`${roundInfo(s).label} 초밥집: ${option.unit?D.units[option.unit].name:'골드'} + ${D.items[option.item].name}`);for(const p of s.players.slice(1).filter(p=>p.hp>0))takeCarousel(s,p,pick(s,carouselOptions(s)));s.reward=null;advanceRound(s);}else if(reward.type==='augment'){grantAugment(s.players[0],option);log(s,`${D.augments[option].name} 획득`);s.reward=null;}else return false;return true;}

  function audit(s){const used=Object.fromEntries(Object.keys(D.units).map(id=>[id,0]));for(const p of s.players){for(const id of p.shop)if(id)used[id]++;for(const u of all(p))used[u.id]+=3**(u.star-1);}return Object.keys(used).filter(id=>s.pool[id]<0||used[id]+s.pool[id]!==D.poolSizes[D.units[id].cost]);}
  const api={roundInfo,stageDamage,creepTeam,newGame,random,copy,createUnit,roll,buy,sell,move,buyXp,addXp,equip,unequip,recipeFor,canCraft,craft,traits,all,combine,prepareRound,opponent,startRound,finishRound,chooseReward,collectLoot,moveLegend,setLegend,setDifficulty,createBattle,stepBattle,simulate,audit,log,aiTurn};root.ArenaEngine=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
