/* Browser UI. Simulation and persistent state live in engine.js. */
(() => {
  'use strict';
  const E=window.ArenaEngine,D=window.ArenaData,$=s=>document.querySelector(s),KEY='file-island-league-v8';
  let state,selected=null,inspect=null,itemSelected=null,scout=1,speed=2,active=null,timer=null,lastEvents=0,toastTimer;
  function load(){try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved?.version===8&&D.difficulties[saved.difficulty]&&['prep','over'].includes(saved.phase)&&saved.players?.length===8&&E.audit(saved).length===0)return saved;}catch{}return E.newGame();}
  function save(){if(state.phase==='battle')return;try{localStorage.setItem(KEY,JSON.stringify(state));$('#saveStatus').textContent='준비 단계 자동 저장 · 인터넷 없이 플레이';}catch{$('#saveStatus').textContent='저장 공간을 사용할 수 없습니다 · 이번 창에서 플레이 가능';}}
  function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2600);}
  const me=()=>state.players[0];
  const preview=()=>scout===-1?E.creepTeam(state):state.players[scout];
  const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const sprite=name=>`<img class="sprite" src="assets/${name}.gif" alt="" draggable="false">`;
  const unitDef=id=>D.units[id]||D.creeps[id];
  function unitCard(u,battle=false){
    const d=unitDef(u.id),sel=selected&&me()[selected.area]?.[selected.i]?.uid===u.uid;
    return `<div class="unit ${sel?'selected':''} ${battle?'battling':''} ${battle&&u.flash>active.visible.combat.time?'hit':''}" style="--rarity:${D.colors[d.cost]}"><span class="stars">${'★'.repeat(u.star)}</span>${sprite(d.sprite)}<span class="unit-name">${escape(d.name)}</span><span class="unit-items">${u.items.map(i=>`<span title="${D.items[i].name}">${D.items[i].icon}</span>`).join('')}</span>${battle?`<div class="bars"><div class="bar"><i style="width:${Math.max(0,u.hp/u.max*100)}%"></i></div><div class="bar mana"><i style="width:${u.mana}%"></i></div></div>`:''}</div>`;
  }
  function board(){let slots=Array(56).fill(null);const battle=state.phase==='battle'&&active;if(battle){for(const u of active.visible.combat.units)if(u.hp>0)slots[u.y*7+u.x]=u;}else{preview().board.forEach((u,i)=>{if(u)slots[(3-Math.floor(i/7))*7+i%7]=u;});me().board.forEach((u,i)=>slots[28+i]=u);}
    $('#board').innerHTML=slots.map((u,i)=>`<button class="cell ${battle?(u?.side===1?'enemy':''):i<28?'enemy':''}" data-cell="${i}" ${battle&&u?.side!==0?'disabled':''} aria-label="${i<28?'상대':'내'} ${Math.floor(i/7)%4+1}행 ${i%7+1}열${u?' '+escape(D.units[u.id].name)+' '+u.star+'성':' 빈칸'}" ${!battle&&i>=28&&u?'draggable="true"':''}>${u?unitCard(u,!!battle):`<span class="cell-index">${i%7+1}</span>`}</button>`).join('');
    $('#boardCapacity').textContent=`내 팀 ${me().board.filter(Boolean).length} / ${me().level}`;
    if(battle){const b=active.visible.combat;$('#battleClock').textContent=`${Math.floor(b.time)}s / 45s`;$('#battleStatus').textContent=b.time>=30?'OVERTIME / 피해량 증가':'AUTO BATTLE';$('#effects').innerHTML=b.effects.map(e=>`<line x1="${e.x*100+50}" y1="${e.y*100+50}" x2="${e.tx*100+50}" y2="${e.ty*100+50}" stroke="${e.kind==='skill'?'#e8d37b':e.side===0?'#a3dec9':'#f0b0a7'}" stroke-width="${e.kind==='skill'?5:2}" opacity=".75"/>`).join('');}else{$('#battleClock').textContent='VS';$('#battleStatus').textContent=E.roundInfo(state).name;$('#effects').innerHTML='';}
  }
  function detail(){const target=inspect;if(!target)return;const u=target.uid?E.all(state.players[target.owner||0]).find(x=>x.uid===target.uid):null;const d=D.units[u?.id||target.id];if(!d)return;const star=u?.star||1,scale=[0,1,1.8,3.24][star];$('#detail').innerHTML=`<div class="detail-head">${sprite(d.sprite)}<div><h3>${d.name} <span style="color:${D.colors[d.cost]}">${d.cost}G</span></h3><p>${'★'.repeat(star)} · ${d.stage} · ${D.roles[d.role]}</p><p>${d.attr} / ${d.family}</p></div></div><div class="detail-stats"><div><small>기본 체력</small><b>${Math.round(d.hp*scale)}</b></div><div><small>기본 공격</small><b>${Math.round(d.atk*scale)}</b></div><div><small>공격 / 초</small><b>${d.speed}</b></div><div><small>사거리</small><b>${d.range}칸</b></div></div><div class="detail-skill"><b>${D.skills[d.skill].name}</b><p>${D.skills[d.skill].description}</p></div><div class="stage-info"><b>${d.cost}코스트 · ${d.stage}</b><br>고정 유닛 · 같은 유닛 3개로 별 승급<br>별이 올라가도 이름과 성장 단계는 유지됩니다.</div>${u?`<div class="detail-items">${u.items.map((id,i)=>`<button data-unequip="${i}" ${state.phase!=='prep'||target.owner?'disabled':''} title="${D.items[id].description}">${D.items[id].icon} ${D.items[id].name}${!target.owner?' ↩':''}</button>`).join('')||'<span class="muted" style="font-size:9px">장비 없음 · 최대 2개</span>'}</div>`:''}`;}
  function render(){const p=me(),prep=state.phase==='prep'&&!state.reward;renderTimeline();$('#round').textContent=E.roundInfo(state).label;$('#hp').textContent=p.hp;$('#gold').innerHTML=`${p.gold} <em>G</em>`;$('#interest').textContent=`현재 이자 +${Math.min(5,Math.floor(p.gold/10))}G · 기본 수입 +5G`;$('#record').textContent=`${p.wins}승 · ${p.last?(p.last==='win'?'연승':p.last==='loss'?'연패':'무승부')+' '+p.streak:'첫 전투 준비'}`;$('#phaseText').textContent=state.phase==='battle'?'조합과 장비의 힘을 확인하세요. 전투 후 팀을 다시 정비할 수 있습니다.':state.phase==='over'?`리그 종료 · 최종 ${state.rank}위`:'상대를 읽고, 문장과 캡슐로 팀을 완성하세요.';$('#opponent').textContent=state.phase==='battle'?active.visible.enemyName:E.roundInfo(state).type==='carousel'?'디지타마 광장 · 초밥집':preview().name;$('#scoutLabel').textContent=scout===-1?E.roundInfo(state).name:scout===E.opponent(state)?'NEXT OPPONENT / 다음 대전':'SCOUTING / 정찰 중';$('#nextOpponent').disabled=!prep;$('#battleBtn').disabled=!prep||!p.board.some(Boolean);$('#battleBtn').innerHTML=state.phase==='battle'?'전투 진행 중…':state.phase==='over'?'리그 종료':`전투 시작 <span>→</span>`;$('#xpBtn').disabled=!prep||p.gold<4||p.level>=9;$('#rerollBtn').disabled=!prep||p.gold<2;$('#lockBtn').disabled=!prep;$('#lockBtn').classList.toggle('locked',p.locked);$('#lockBtn').setAttribute('aria-pressed',String(p.locked));$('#lockBtn').textContent=p.locked?'잠금 유지 중':'상점 잠금';$('#level').textContent=`LV. ${p.level}`;$('#xp').textContent=p.level===9?'MAX':`${p.xp} / ${D.xp[p.level]} XP`;$('#xpBar').style.width=p.level===9?'100%':`${p.xp/D.xp[p.level]*100}%`;$('#odds').innerHTML=D.odds[p.level].map((n,i)=>`<span style="--rarity:${D.colors[i+1]}"><i></i>${i+1}G ${D.stages[i+1]} ${n}%</span>`).join('');
    const ts=E.traits(p.board.filter(Boolean)).filter(t=>t.count);$('#traitCount').textContent=String(ts.filter(t=>t.tier).length).padStart(2,'0');$('#synergies').innerHTML=ts.sort((a,b)=>b.tier-a.tier||b.count-a.count).map(t=>`<div class="trait ${t.tier?'active':''}"><span class="trait-icon">${{'백신':'✧','데이터':'⌘','바이러스':'✦','용형':'♜','야수형':'⋀','곤충형':'⚡','식물형':'❋','천사형':'◇','조류형':'≋'}[t.name]}</span><div class="trait-copy">${t.name}<small>${t.tier?t.description:'다음: '+t.description}</small></div><span class="trait-count">${t.count}/${t.cuts.find(n=>n>t.count)||t.cuts.at(-1)}</span></div>`).join('')||'<p class="empty-note">유닛을 배치해 시너지를 활성화하세요.</p>';
    $('#augments').innerHTML=p.augments.map(id=>`<div class="augment"><span>${D.augments[id].icon}</span>${D.augments[id].name}<small>${D.augments[id].description}</small></div>`).join('')||'<p class="empty-note">2-1 · 3-1 · 4-1<br>당신의 팀을 위한 지원을 선택하세요.</p>';
    $('#itemCount').textContent=p.inventory.length;
    $('#inventory').innerHTML=p.inventory.map((id,i)=>`<button class="inventory-item ${D.items[id].kind} ${itemSelected===i?'selected':''}" data-item="${i}" title="${D.items[id].name} · ${D.items[id].description}" aria-label="${D.items[id].name}: ${D.items[id].description}" ${!prep?'disabled':''}><span>${D.items[id].icon}</span><b>${D.items[id].name}</b><small>${D.items[id].kind==='component'?'재료':'완성'}</small></button>`).join('')||'<span class="empty-note">보관 중인 장비가 없습니다.</span>';
    const chosen=D.items[p.inventory[itemSelected]];
    $('#itemDetail').innerHTML=chosen?`<b>${chosen.name}</b><p>${chosen.description}</p><small>${chosen.kind==='component'?'아군 클릭 → 장착 / 기존 재료가 있으면 자동 합성':'아군을 클릭해 장착하세요.'}</small>`:'재료 2개 → 문장 또는 캡슐<br>합성소에서 모든 조합법을 확인하세요.';
    $('#craftBtn').disabled=!prep;
    $('#benchCount').textContent=`${p.bench.filter(Boolean).length} / 9`;$('#bench').innerHTML=p.bench.map((u,i)=>`<button class="bench-slot" data-bench="${i}" aria-label="대기석 ${i+1}${u?' '+D.units[u.id].name:' 빈칸'}" ${u&&prep?'draggable="true"':''}>${u?unitCard(u):`<span class="cell-index">${i+1}</span>`}</button>`).join('');$('#sellBtn').disabled=!prep||!selected;$('#sellBtn').textContent=selected&&p[selected.area][selected.i]?`판매 +${D.units[p[selected.area][selected.i].id].cost*3**(p[selected.area][selected.i].star-1)}G`:'선택 유닛 판매';
    $('#shop').innerHTML=p.shop.map((id,i)=>{if(!id)return '<button class="shop-card sold" disabled>모집 완료</button>';const d=D.units[id];return `<button class="shop-card" data-buy="${i}" data-inspect="${id}" style="--rarity:${D.colors[d.cost]}" ${!prep?'disabled':''} aria-label="${d.name} ${d.cost}골드 모집"><div class="portrait"><span class="role-tag">${d.stage} · ${D.roles[d.role]}</span>${sprite(d.sprite)}<span class="cost">${d.cost} G</span></div><div class="card-copy"><h3>${d.name}</h3><p>${d.attr} · ${d.family}</p><span class="pool-count">POOL ${state.pool[id]}</span></div></button>`;}).join('');
    $('#standings').innerHTML=[...state.players].sort((a,b)=>b.hp-a.hp||b.wins-a.wins||a.id-b.id).map((x,i)=>`<button class="standing ${x.id===0?'mine':''} ${x.id===scout?'scouted':''} ${x.hp<=0?'dead':''}" data-scout="${x.id}" ${x.id===0||x.hp<=0||state.phase==='battle'?'disabled':''}><span class="rank">${i+1}</span><span class="tamer-avatar">${x.id===0?'나':String(x.id).padStart(2,'0')}</span><span class="standing-copy">${x.name}<small>${x.hp>0?`LV.${x.level} · ${x.wins}승${x.id===E.opponent(state)?' · 다음 상대':''}`:'탈락'}</small><span class="hp-line" style="display:block"><i style="width:${x.hp}%"></i></span></span><span class="standing-hp">${x.hp}</span></button>`).join('');
    $('#interactionHint').textContent=itemSelected!==null?'장비를 받을 아군 유닛을 클릭하세요.':selected?'이동할 칸 클릭 · 같은 유닛 클릭으로 취소':'유닛 선택 후 이동할 칸을 클릭하세요.';board();detail();renderResults();showReward();save();}
  function renderResults(){const r=state.lastResult;if(!r){$('#results').innerHTML='<p class="empty-note">첫 전투 이후 피해량과<br>스킬 사용 횟수가 표시됩니다.</p>';return;}$('#resultTitle').textContent=`R${r.round} · 전투 분석`;const max=Math.max(1,...r.stats.map(u=>u.damage));$('#results').innerHTML=`<p class="result-summary ${r.win?'win':'loss'}">${r.draw?'무승부':r.win?'승리':'패배'} · ${r.damage?'체력 -'+r.damage:'체력 보존'}</p>`+(r.drops?.length?`<div class="loot-summary"><b>토벌 전리품</b><p>${r.drops.map(escape).join(' · ')}</p></div>`:'')+r.stats.slice(0,5).map(u=>`<div class="damage-row" title="스킬 ${u.casts}회 · 회복 ${u.healing}"><div><span>${u.name}</span><span>${u.damage.toLocaleString()}</span></div><div class="damage-track"><i style="width:${u.damage/max*100}%"></i></div></div>`).join('');}
  function renderCraft(){
    const p=me();$('#recipeList').innerHTML=D.completedItems.map(id=>{const d=D.items[id],ready=E.canCraft(p,id)&&['prep','battle'].includes(state.phase)&&!state.reward;
      const needed={};d.recipe.forEach(part=>needed[part]=(needed[part]||0)+1);
      return `<article class="recipe-card ${ready?'ready':''}"><div class="recipe-title"><span>${d.icon}</span><div><b>${d.name}</b><small>완성 아이템 · 장착 1칸</small></div></div><p>${d.description}</p><div class="ingredients">${Object.entries(needed).map(([part,n])=>{const have=p.inventory.filter(x=>x===part).length;return `<span class="${have>=n?'enough':'missing'}">${D.items[part].icon} ${D.items[part].name} <b>${have}/${n}</b></span>`;}).join('<i>+</i>')}</div><button data-craft="${id}" ${!ready?'disabled':''}>${ready?'합성하기 →':'재료 부족'}</button></article>`;
    }).join('');
  }
  function showReward(){if(!state.reward)return;const carousel=state.reward.type==='carousel';$('#rewardTitle').textContent=carousel?`${E.roundInfo(state).label} · 디지타마 광장`:'테이머 지원을 선택하세요.';$('#rewardOptions').innerHTML=state.reward.options.map((option,i)=>carousel?`<button class="reward-card carousel-card" data-reward="${i}">${option.unit?sprite(D.units[option.unit].sprite):'<span>G</span>'}<b>${option.unit?D.units[option.unit].name:'골드 보급'}</b><p>${option.unit?D.units[option.unit].cost+'G · '+D.units[option.unit].stage:'공유 재고 소진 시 골드 지급'}</p><strong>${D.items[option.item].icon} ${D.items[option.item].name}</strong><p>${D.items[option.item].description}</p><small>유닛 + 아이템 획득<br>대기석 포화 시 유닛은 판매가로 전환</small></button>`:`<button class="reward-card" data-reward="${i}"><span>${D.augments[option].icon}</span><b>${D.augments[option].name}</b><p>${D.augments[option].description}</p></button>`).join('');if(!$('#reward').open)$('#reward').showModal();}
  function renderTimeline(){const info=E.roundInfo(state),start=info.stage===1?1:4+(info.stage-2)*7;$('#roundTrack').innerHTML=Array.from({length:info.stage===1?3:7},(_,i)=>{const r=E.roundInfo(start+i);return `<div class="round-node ${r.type} ${r.step===info.step?'current':''} ${r.step<info.step?'passed':''}"><b>${r.label}</b><span>${r.type==='creep'?'◆ 크립':r.type==='carousel'?'✦ 초밥집':'⚔ PvP'}</span></div>`;}).join('');$('#roundHint').textContent=info.type==='pvp'?`패배 피해: 기본 ${2+(info.stage-2)*2} + 상대 생존 별 합계, ×${(1+(info.stage-2)*.1).toFixed(1)} (올림)`:info.type==='creep'?'처치 시 골드 · 완승 시 재료와 유닛 · PvP 연속 기록 유지':'유닛 + 아이템 묶음 하나 선택 · 전투와 수입 정산 없이 다음 라운드';}
  function ensureRound(){if(state.phase==='prep'&&!state.reward&&!state.pairs)E.prepareRound(state);scout=E.opponent(state);}
  function select(area,i){if(!['prep','battle'].includes(state.phase)||state.reward)return;const p=me(),u=p[area][i];if(itemSelected!==null){if(!u){toast('장비를 장착할 유닛을 선택하세요.');return;}if(!E.equip(state,p,u.uid,itemSelected)){toast('장비는 최대 2개입니다. 재료 + 재료는 빈 슬롯 없이도 합성됩니다.');return;}itemSelected=null;inspect={uid:u.uid,owner:0};render();return;}if(selected){if(selected.area===area&&selected.i===i)selected=null;else if(E.move(state,p,selected.area,selected.i,area,i)){selected=null;}else toast(state.phase==='battle'?'전투 중에는 필드 유닛을 이동할 수 없습니다.':'배치 한도가 가득 찼습니다. 레벨을 올리거나 유닛을 교체하세요.');}else if(u){selected={area,i};inspect={uid:u.uid,owner:0};}render();}
  function sell(){if(!selected)return;const u=me()[selected.area][selected.i];if(E.sell(state,me(),selected.area,selected.i)){toast(`${D.units[u.id].name} 판매 완료 · 장비 회수`);selected=null;inspect=null;$('#detail').innerHTML='<div class="empty-detail">유닛을 선택해 정보를 확인하세요.</div>';render();}}
  function runBattle(){const r=E.startRound(state);if(!r){toast(state.reward?'먼저 보상을 선택하세요.':'전장에 유닛을 배치하세요.');return;}active=r;selected=null;itemSelected=null;scout=r.visible.b;lastEvents=0;render();timer=setInterval(()=>{for(let i=0;i<speed;i++)E.stepBattle(r.visible.combat,.1);board();const events=r.visible.combat.events;if(events.length>lastEvents){$('#battleStatus').textContent=events.at(-1);lastEvents=events.length;}if(r.visible.combat.done){clearInterval(timer);timer=null;events.forEach(t=>E.log(state,t));E.finishRound(state,r);const eliminated=state.lastResult.type==='pvp'&&state.lastResult.win&&r.visible.b>=0&&state.players[r.visible.b].hp<=0,fx=state.lastResult.win?playVictoryFx(eliminated):0;active=null;ensureRound();render();if(state.phase==='over')setTimeout(showEnd,fx);else toast(state.lastResult.win?(eliminated?'승리 · 상대 테이머 처형!':'승리! 다음 라운드를 준비하세요.'):state.lastResult.draw?'시간 초과 · 전투 결과와 피해를 확인하세요.':'전투 종료 · 전열과 배치를 점검해보세요.');}},100);}
  function showEnd(){$('#endTitle').textContent=state.rank===1?'리그 챔피언!':`최종 ${state.rank}위`;$('#endText').textContent=`${E.roundInfo(state).label} · ${me().wins}승. ${state.rank===1?'당신의 팀이 파일 아일랜드를 지켜냈습니다.':'새로운 조합과 장비 합성으로 다시 도전해보세요.'}`;$('#end').showModal();}
  function reset(){clearInterval(timer);timer=null;active=null;document.querySelectorAll('dialog[open]').forEach(d=>d.close());state=E.newGame();selected=null;inspect=null;itemSelected=null;ensureRound();$('#detail').innerHTML='<div class="empty-detail">유닛을 선택해 성장 단계와 장비를 확인하세요.</div>';render();openLobby();}
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.close){$('#'+b.dataset.close).close();return;}if(b.dataset.cell!==undefined){const i=+b.dataset.cell;if(i>=28)select('board',i-28);else if(state.phase!=='battle'){const pos=(3-Math.floor(i/7))*7+i%7,u=preview().board[pos];if(u){inspect=scout===-1?{id:u.id}:{uid:u.uid,owner:scout};detail();}}}if(b.dataset.bench!==undefined)select('bench',+b.dataset.bench);if(b.dataset.buy!==undefined){const id=me().shop[+b.dataset.buy];if(E.buy(state,me(),+b.dataset.buy)){selected=null;inspect={id};render();}else toast(me().gold<D.units[id].cost?'골드가 부족합니다.':'대기석이 가득 찼습니다. 판매하거나 합성 공간을 확보하세요.');}if(b.dataset.scout!==undefined&&state.phase!=='battle'){scout=+b.dataset.scout;render();}if(b.dataset.item!==undefined){itemSelected=itemSelected===+b.dataset.item?null:+b.dataset.item;selected=null;render();}if(b.dataset.unequip!==undefined&&inspect){E.unequip(state,me(),inspect.uid,+b.dataset.unequip);render();}if(b.dataset.craft!==undefined){if(E.craft(state,me(),b.dataset.craft)){itemSelected=null;toast(D.items[b.dataset.craft].name+' 합성 완료! 보관함에 추가됐습니다.');render();renderCraft();}}if(b.dataset.reward!==undefined){if(!E.chooseReward(state,+b.dataset.reward))return;$('#reward').close();ensureRound();render();}});
  $('#shop').addEventListener('mouseover',e=>{const el=e.target.closest('[data-inspect]');if(el){inspect={id:el.dataset.inspect};detail();}});$('#shop').addEventListener('focusin',e=>{const el=e.target.closest('[data-inspect]');if(el){inspect={id:el.dataset.inspect};detail();}});
  $('#craftBtn').onclick=()=>{renderCraft();$('#crafting').showModal();};
  $('#rerollBtn').onclick=()=>{if(E.roll(state,me()))render();};$('#xpBtn').onclick=()=>{if(E.buyXp(state,me()))render();};$('#lockBtn').onclick=()=>{if(state.phase==='prep'){me().locked=!me().locked;render();}};$('#battleBtn').onclick=runBattle;$('#speedBtn').onclick=()=>{speed=speed===1?2:speed===2?4:1;$('#speedBtn').textContent=`속도 ×${speed}`;};$('#nextOpponent').onclick=()=>{scout=E.opponent(state);render();};$('#sellBtn').onclick=sell;$('#helpBtn').onclick=()=>$('#help').showModal();$('#newBtn').onclick=()=>$('#reset').showModal();$('#endNew').onclick=reset;$('#confirmReset').onclick=reset;$('#logBtn').onclick=()=>{$('#logList').innerHTML=state.logs.map(t=>`<p>${escape(t)}</p>`).join('');$('#logs').showModal();};$('#reward').addEventListener('cancel',e=>e.preventDefault());
  document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')||document.querySelector('dialog[open]'))return;if(e.key==='Escape'){selected=null;itemSelected=null;render();}if(e.key==='?')$('#help').showModal();if(!['prep','battle'].includes(state.phase))return;if(e.key.toLowerCase()==='d')$('#rerollBtn').click();if(e.key.toLowerCase()==='f')$('#xpBtn').click();if(e.key.toLowerCase()==='e'&&(state.phase==='prep'||selected?.area==='bench'))sell();});
  document.addEventListener('contextmenu',e=>{const el=e.target.closest('[data-cell],[data-bench]');if(!el)return;e.preventDefault();if(!['prep','battle'].includes(state.phase))return;const area=el.dataset.bench!==undefined?'bench':'board',i=area==='bench'?+el.dataset.bench:+el.dataset.cell-28;if(state.phase==='battle'&&area==='board')return;if(i>=0&&me()[area][i]){selected={area,i};sell();}});
  document.addEventListener('dragstart',e=>{const el=e.target.closest('[draggable="true"]');if(!el||!['prep','battle'].includes(state.phase))return;const area=el.dataset.bench!==undefined?'bench':'board',i=area==='bench'?+el.dataset.bench:+el.dataset.cell-28;if(state.phase==='battle'&&area==='board')return;e.dataTransfer.setData('text/plain',JSON.stringify({area,i}));e.dataTransfer.effectAllowed='move';});
  document.addEventListener('dragover',e=>{const el=e.target.closest('[data-cell],[data-bench]');if(el&&(el.dataset.bench!==undefined||+el.dataset.cell>=28)){e.preventDefault();e.dataTransfer.dropEffect='move';}});
  document.addEventListener('drop',e=>{const el=e.target.closest('[data-cell],[data-bench]');if(!el)return;e.preventDefault();try{const from=JSON.parse(e.dataTransfer.getData('text/plain')),area=el.dataset.bench!==undefined?'bench':'board',i=area==='bench'?+el.dataset.bench:+el.dataset.cell-28;if(!E.move(state,me(),from.area,from.i,area,i))toast('이 위치로 이동할 수 없습니다. 배치 한도를 확인하세요.');selected=null;render();}catch{}});
  function legendVisual(l,css=''){return l.sprite?sprite(l.sprite).replace('class="sprite"',`class="sprite ${css}"`):`<span class="legend-glyph ${css}">${l.glyph}</span>`;}
  function renderLoot(){const layer=$('#lootLayer');if(!layer)return;const prep=state.phase==='prep',l=D.legends[state.legend.id]||D.legends.bitmon;layer.innerHTML=state.pendingLoot.filter(o=>o.owner===0).map(o=>`<button class="loot-orb ${o.rarity}" data-loot="${o.id}" style="left:${o.x}%;top:${o.y}%" aria-label="전리품 구슬"><i></i></button>`).join('')+`<button id="legend" class="legend legend-${l.id} ${prep?'':'watching'}" style="left:${state.legend.x}%;top:${state.legend.y}%;--legend-color:${l.color}" ${prep?'':'disabled'} aria-label="${l.name}">${legendVisual(l)}<b>${l.name}</b></button>`;}
  function renderLobby(){const selected=state.legend.id,difficulty=D.difficulties[state.difficulty]||D.difficulties.normal;$('#legendChoices').innerHTML=Object.values(D.legends).map(l=>`<button class="legend-choice ${l.id===selected?'selected':''}" data-legend="${l.id}" style="--legend-color:${l.color}" aria-pressed="${l.id===selected}">${legendVisual(l,'choice-sprite')}<b>${l.name}</b><small>${l.finisher}</small></button>`).join('');$('#difficultyChoices').innerHTML=Object.values(D.difficulties).map(d=>`<button class="difficulty-choice ${d.id===difficulty.id?'selected':''}" data-difficulty="${d.id}" aria-pressed="${d.id===difficulty.id}"><b>${d.name}</b><small>${d.id==='easy'?'처음 플레이':d.id==='normal'?'기본 난이도':'숙련자 추천'}</small></button>`).join('');$('#difficultyDetail').innerHTML=`<b>${difficulty.name}</b><span>${difficulty.description}</span>`;$('#enterBtn').innerHTML=`${difficulty.name} · 솔로 리그 입장 <span>→</span>`;}
  function openLobby(){renderLobby();$('#lobby').classList.add('open');}
  function playVictoryFx(eliminated){const l=D.legends[state.legend.id]||D.legends.bitmon,layer=$('#combatCinematic'),duration=eliminated?2300:1050;layer.className=`combat-cinematic show ${eliminated?'finisher':'boom'} ${l.boom}`;layer.style.setProperty?.('--legend-color',l.color);layer.innerHTML=`<div class="cinematic-flash"></div><div class="cinematic-attacker">${legendVisual(l)}<b>${l.name}</b></div><div class="cinematic-shot"></div><div class="cinematic-target"><i></i><strong>${eliminated?l.finisher:'승리 공격!'}</strong><small>${eliminated?'상대 테이머 탈락':'상대에게 피해 전달'}</small></div>`;setTimeout(()=>{layer.className='combat-cinematic';layer.innerHTML='';},duration);return duration;}
  function collectOrb(id){const orb=state.pendingLoot.find(o=>o.id===id&&o.owner===0);if(!orb)return;E.moveLegend(state,orb.x,orb.y);const rewards=E.collectLoot(state,id);if(rewards){toast(`전리품 획득 · ${rewards.join(' · ')}`);render();}}
  $('#board').addEventListener('click',e=>{if(state.phase!=='battle')return;const cell=e.target.closest('[data-cell]');if(!cell)return;const i=+cell.dataset.cell,u=active?.visible.combat.units.find(x=>x.hp>0&&x.side===0&&x.y*7+x.x===i);if(!u)return;e.stopPropagation();if(itemSelected!==null){if(E.equip(state,me(),u.uid,itemSelected)){itemSelected=null;inspect={uid:u.uid,owner:0};toast('장착 완료 · 다음 전투부터 능력치에 적용됩니다.');render();}else toast('장비는 최대 2개입니다.');}else{const owned=E.all(me()).find(x=>x.uid===u.uid);if(owned){inspect={uid:owned.uid,owner:0};detail();}}});
  $('#lootLayer').addEventListener('click',e=>{const orb=e.target.closest('[data-loot]');if(orb?.dataset.loot!==undefined){e.stopPropagation?.();collectOrb(orb.dataset.loot);}});
  $('#arena').addEventListener('click',e=>{if(state.phase!=='prep'||e.target.closest('button'))return;const box=$('#arena').getBoundingClientRect();E.moveLegend(state,(e.clientX-box.left)/box.width*100,(e.clientY-box.top)/box.height*100);renderLoot();save();});
  const renderTimelineBase=renderTimeline;renderTimeline=()=>{renderTimelineBase();if(E.roundInfo(state).type==='creep')$('#roundHint').textContent='악당 디지몬 처치마다 구슬 드롭 판정 · 보드의 구슬을 비트몬으로 직접 회수 · PvP 연속 기록 유지';};
  function enableCombatManagement(){if(state.phase!=='battle')return;$('#xpBtn').disabled=me().gold<4||me().level>=9;$('#rerollBtn').disabled=me().gold<2;$('#lockBtn').disabled=false;$('#craftBtn').disabled=false;$('#sellBtn').disabled=!selected||selected.area!=='bench';document.querySelectorAll('#shop [data-buy],#inventory [data-item],#detail [data-unequip]').forEach(el=>el.removeAttribute('disabled'));document.querySelectorAll('#bench [data-bench]').forEach((el,i)=>{if(me().bench[i])el.setAttribute('draggable','true');});document.querySelectorAll('#board .cell').forEach(el=>{const i=+el.dataset.cell,u=active?.visible.combat.units.find(x=>x.hp>0&&x.y*7+x.x===i);if(u?.side===0)el.removeAttribute('disabled');});$('#lockBtn').onclick=()=>{me().locked=!me().locked;render();};}
  const renderBase=render;render=()=>{renderBase();renderLoot();enableCombatManagement();};
  $('#legendChoices').addEventListener('click',e=>{const choice=e.target.closest('[data-legend]');if(!choice||!E.setLegend(state,choice.dataset.legend))return;renderLobby();renderLoot();save();});
  $('#difficultyChoices').addEventListener('click',e=>{const choice=e.target.closest('[data-difficulty]');if(!choice||!E.setDifficulty(state,choice.dataset.difficulty))return;renderLobby();save();});
  $('#enterBtn').onclick=()=>{$('#lobby').classList.remove('open');save();if(state.phase==='over')showEnd();};
  state=load();ensureRound();render();openLobby();
})();
