'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const E=require('../engine.js'),D=require('../data.js');
function owned(s,p,id,star=1,area='bench',i=p[area].indexOf(null)){s.pool[id]-=3**(star-1);const u=E.createUnit(s,id,star);p[area][i]=u;return u;}
function empty(s,p){for(const area of ['board','bench'])for(let i=0;i<p[area].length;i++)if(p[area][i])E.sell(s,p,area,i);}
function reserve(s,p,id,i=0){if(p.shop[i])s.pool[p.shop[i]]++;p.shop[i]=id;s.pool[id]--;}
function fixture(a,b){const s=E.newGame(77),p=s.players[0],q=s.players[1];empty(s,p);empty(s,q);a.forEach(([id,pos,star=1])=>owned(s,p,id,star,'board',pos));b.forEach(([id,pos,star=1])=>owned(s,q,id,star,'board',pos));return {s,p,q};}
test('all sprites exist, odds total 100, trait thresholds are reachable',()=>{for(const d of Object.values(D.units)){for(const image of [d.sprite])assert.ok(fs.existsSync(path.join(__dirname,'../assets',image+'.gif')),image);assert.ok(D.skills[d.skill]);}for(const odds of Object.values(D.odds))assert.equal(odds.reduce((a,b)=>a+b),100);for(const [name,t]of Object.entries(D.traits))assert.ok(Object.values(D.units).filter(d=>d.attr===name||d.family===name).length>=t.cuts.at(-1),name);});
test('pool is conserved through 500 refreshes and buying/selling',()=>{const s=E.newGame(1),p=s.players[0];assert.deepEqual(E.audit(s),[]);p.gold=100000;for(let n=0;n<500;n++){E.roll(s,p);E.buy(s,p,n%5);if(n%4===0){const i=p.bench.findIndex(Boolean);if(i>=0)E.sell(s,p,'bench',i);}assert.deepEqual(E.audit(s),[]);}assert.ok(Object.values(s.pool).every(n=>n>=0));});
test('pool uses the requested cost counts and three-star units leave only their owner shop',()=>{assert.deepEqual(D.poolSizes,{'1':39,'2':26,'3':21,'4':13,'5':10});const s=E.newGame(91),p=s.players[0],q=s.players[1];empty(s,p);for(const player of [p,q])for(let i=0;i<player.shop.length;i++){if(player.shop[i])s.pool[player.shop[i]]++;player.shop[i]=null;}reserve(s,q,'koromon');for(let i=0;i<9;i++)owned(s,p,'koromon',1,'bench',i);reserve(s,p,'koromon',0);E.combine(s,p);assert.ok(E.all(p).some(u=>u.id==='koromon'&&u.star===3));assert.ok(p.shop.every(id=>id!=='koromon'));assert.equal(q.shop[0],'koromon');p.gold=1000;for(let i=0;i<100;i++){E.roll(s,p);assert.ok(p.shop.every(id=>id!=='koromon'));}assert.deepEqual(E.audit(s),[]);});
test('three-star chain preserves copies and returns excess items',()=>{const s=E.newGame(2),p=s.players[0];empty(s,p);for(let i=0;i<9;i++){owned(s,p,'agumon',1,'bench',i).items=['courage'];}const items=p.inventory.length;E.combine(s,p);const units=E.all(p);assert.equal(units.length,1);assert.equal(units[0].star,3);assert.equal(units[0].items.length,2);assert.equal(p.inventory.length,items+7);assert.deepEqual(E.audit(s),[]);});
test('full bench permits immediate combine without losing any other unit',()=>{const s=E.newGame(3),p=s.players[0];empty(s,p);const ids=['palmon','palmon','agumon','gabumon','tentomon','piyomon','patamon','togemon','garurumon'];ids.forEach((id,i)=>owned(s,p,id,1,'bench',i));const preserved=p.bench.slice(2).map(u=>u.uid);reserve(s,p,'palmon');p.gold=99;assert.equal(E.buy(s,p,0),true);assert.equal(p.bench.length,9);assert.equal(p.bench.filter(Boolean).length,8);assert.equal(p.bench.find(u=>u?.id==='palmon').star,2);assert.ok(preserved.every(uid=>E.all(p).some(u=>u.uid===uid)));assert.deepEqual(E.audit(s),[]);});
test('combat locks field movement and field sales but keeps economy and bench actions open',()=>{const s=E.newGame(4),p=s.players[0];p.gold=99;p.level=3;p.inventory=['courage'];owned(s,p,'mochimon',1,'board',1);const field=owned(s,p,'tanemon',1,'board',2),bench=owned(s,p,'tentomon');s.phase='battle';assert.equal(E.move(s,p,'board',3,'bench',1),false);assert.equal(E.move(s,p,'bench',0,'board',0),false);assert.equal(E.sell(s,p,'board',2),false);assert.equal(E.equip(s,p,field.uid,0),true);assert.deepEqual(field.items,['courage']);assert.equal(E.roll(s,p),true);assert.equal(E.buy(s,p,0),true);const level=p.level;assert.equal(E.buyXp(s,p),true);assert.ok(p.level>level||p.xp>0);assert.equal(E.sell(s,p,'bench',p.bench.findIndex(u=>u?.uid===bench.uid)),true);assert.deepEqual(E.audit(s),[]);});
test('traits count different base units, not stars or duplicates',()=>{const s=E.newGame(8);const same=[E.createUnit(s,'agumon'),E.createUnit(s,'agumon',2)];assert.equal(E.traits(same).find(t=>t.name==='백신').count,1);same.push(E.createUnit(s,'tentomon'));assert.equal(E.traits(same).find(t=>t.name==='백신').tier,1);});
test('seeded fights reproduce exactly and do not mutate owned boards',()=>{const {p,q}=fixture([['agumon',3],['gabumon',24],['palmon',26]],[['tentomon',3],['piyomon',24]]);const before=JSON.stringify([p,q]),a=E.simulate(E.createBattle(p,q,125)),b=E.simulate(E.createBattle(p,q,125));assert.deepEqual(a,b);assert.equal(JSON.stringify([p,q]),before);assert.ok(a.done);assert.ok(a.units.every(u=>Number.isFinite(u.hp)&&u.hp>=0&&u.hp<=u.max));});
test('ranged fighters attack in range without moving to melee',()=>{const {p,q}=fixture([['gabumon',3]],[['tentomon',17]]);const b=E.createBattle(p,q,22),u=b.units.find(u=>u.side===0);const xy=[u.x,u.y];for(let i=0;i<4;i++)E.stepBattle(b);assert.deepEqual([u.x,u.y],xy);assert.ok(u.damage>0);});
test('pathfinding never overlaps living units or leaves the board',()=>{const {p,q}=fixture([['agumon',0],['greymon',1],['togemon',2],['angemon',3],['gabumon',4],['palmon',10]],[['tentomon',0],['greymon',1],['togemon',2],['angemon',3],['piyomon',4],['lilimon',10]]);const b=E.createBattle(p,q,412);while(!b.done){E.stepBattle(b);const alive=b.units.filter(u=>u.hp>0);assert.equal(new Set(alive.map(u=>u.y*7+u.x)).size,alive.length);for(const u of alive)assert.ok(u.x>=0&&u.x<7&&u.y>=0&&u.y<8);} });
test('timeout is a draw, not an automatic player win',()=>{const {p,q}=fixture([['agumon',3]],[['agumon',3]]),b=E.createBattle(p,q,2);b.units.forEach(u=>{u.hp=u.max=1e12;u.atk=0;});E.simulate(b);assert.equal(b.winner,null);assert.ok(b.time>=45);});
test('dead fighters do not act later in the same step',()=>{const {p,q}=fixture([['agumon',3]],[['agumon',3]]);for(let seed=0;seed<30;seed++){const b=E.createBattle(p,q,seed);b.units.forEach(u=>{u.hp=1;u.atk=999999;u.cd=0;});E.stepBattle(b);assert.equal(b.units.filter(u=>u.hp>0).length,1);assert.equal(b.units.filter(u=>u.damage>0).length,1);}});
test('fixed-stage units never transform during combat',()=>{const {p,q}=fixture([['metalgreymon',3],['weregarurumon',4]],[['tentomon',3,3]]),b=E.createBattle(p,q,1);E.simulate(b);for(const u of b.units){assert.equal(u.name,D.units[u.id].name);assert.equal(u.sprite,D.units[u.id].sprite);assert.equal('dp' in u,false);assert.equal('evolved' in u,false);assert.equal('jogress' in u,false);}assert.ok(!b.events.some(e=>/진화|조그레스/.test(e)));});
test('healing, shield, area damage and stun skills have distinct effects',()=>{const {p,q}=fixture([['palmon',3],['patamon',4],['tentomon',2]],[['agumon',2],['agumon',4]]),b=E.createBattle(p,q,2);const team=b.units.filter(u=>u.side===0);team.forEach(u=>{u.hp*=.5;u.mana=100;});E.stepBattle(b);assert.ok(team.find(u=>u.id==='palmon').healing>0);assert.ok(team.some(u=>u.shield>0));assert.ok(b.units.some(u=>u.side===1&&u.stun>b.time));assert.ok(b.units.filter(u=>u.side===1).every(u=>u.hp<u.max));});
test('reward selection cannot be repeated and survives serialization',()=>{const s=E.newGame(10);s.reward={type:'augment',options:['economy','scholar','fortress']};const gold=s.players[0].gold;assert.equal(E.chooseReward(s,0),true);assert.equal(s.players[0].gold,gold+5);assert.equal(E.chooseReward(s,0),false);const saved=JSON.parse(JSON.stringify(s));assert.deepEqual(E.audit(saved),[]);assert.deepEqual(saved.players[0].augments,['economy']);});
test('complete leagues preserve stock, produce one outcome per living player and terminate',()=>{for(let seed=1;seed<=12;seed++){const s=E.newGame(seed);let count=0;while(s.phase!=='over'){if(s.reward)E.chooseReward(s,0);E.prepareRound(s);if(s.reward){E.chooseReward(s,0);continue;}E.aiTurn(s,s.players[0]);E.prepareRound(s);const before=new Map(s.players.filter(p=>p.hp>0).map(p=>[p.id,p.last]));const r=E.startRound(s);assert.ok(r?.visible);E.simulate(r.visible.combat);E.finishRound(s,r);assert.deepEqual(E.audit(s),[],`seed ${seed} round ${s.round}`);if(s.lastResult.type==='pvp')for(const id of before.keys())assert.notEqual(s.players[id].last,null);for(const p of s.players){assert.ok(p.gold>=0);assert.ok(p.board.filter(Boolean).length<=p.level);assert.ok(p.bench.length===9);}assert.ok(++count<=52);}assert.ok(s.rank>=1&&s.rank<=8);}});
test('UI boot and one complete combat/reward cycle run without DOM binding errors',()=>{const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');const nodes=new Map([...html.matchAll(/id="([^"]+)"/g)].map(m=>['#'+m[1],{innerHTML:'',textContent:'',style:{},dataset:{},open:false,disabled:false,classList:{add(){},remove(){},toggle(){}},setAttribute(){},addEventListener(){},showModal(){this.open=true;},close(){this.open=false;},click(){this.onclick?.();}}]));let tick;const handlers={};const storage=new Map();const document={querySelector(s){if(s==='dialog[open]')return [...nodes.values()].find(n=>n.open)||null;assert.ok(nodes.has(s),`missing element ${s}`);return nodes.get(s);},querySelectorAll(){return [];},addEventListener(name,fn){handlers[name]=fn;}};const context={window:{ArenaEngine:E,ArenaData:D},document,localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},setTimeout:()=>0,clearTimeout(){},setInterval:fn=>(tick=fn,1),clearInterval(){tick=null;},console};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../game.js'),'utf8'),context);assert.equal((nodes.get('#legendChoices').innerHTML.match(/data-legend=/g)||[]).length,4);assert.equal((nodes.get('#difficultyChoices').innerHTML.match(/data-difficulty=/g)||[]).length,3);assert.match(nodes.get('#difficultyDetail').innerHTML,/보통/);assert.match(nodes.get('#enterBtn').innerHTML,/보통 · 솔로 리그 입장/);assert.equal(typeof nodes.get('#enterBtn').onclick,'function');assert.match(nodes.get('#board').innerHTML,/data-cell="55"/);assert.match(nodes.get('#shop').innerHTML,/data-buy/);nodes.get('#craftBtn').onclick();assert.equal(nodes.get('#crafting').open,true);assert.match(nodes.get('#recipeList').innerHTML,/우정의 문장/);
const click=dataset=>handlers.click({target:{closest:()=>({dataset})}});nodes.get('#crafting').close();
assert.equal(nodes.get('#round').textContent,'1-1');assert.match(nodes.get('#opponent').textContent,/악의 숲/);
nodes.get('#battleBtn').onclick();assert.ok(nodes.get('#battleBtn').disabled);let calls=0;while(tick){tick();assert.ok(++calls<500);}assert.equal(nodes.get('#round').textContent,'1-2');assert.equal(nodes.get('#reward').open,false);assert.match(nodes.get('#results').innerHTML,/토벌 전리품/);assert.ok(storage.size===1);
for(let i=0;i<2;i++){nodes.get('#battleBtn').onclick();while(tick)tick();}assert.equal(nodes.get('#round').textContent,'2-1');assert.equal(nodes.get('#reward').open,true);click({reward:'0'});assert.equal(nodes.get('#reward').open,false);
for(let i=0;i<3;i++){nodes.get('#battleBtn').onclick();while(tick)tick();}assert.equal(nodes.get('#round').textContent,'2-4');assert.equal(nodes.get('#reward').open,true);assert.match(nodes.get('#rewardOptions').innerHTML,/carousel-card/);click({reward:'0'});assert.equal(nodes.get('#round').textContent,'2-5');assert.equal(nodes.get('#reward').open,false);
});
