'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const E=require('../engine.js'),D=require('../data.js');
function battle(s,win=true){E.prepareRound(s);const r=E.startRound(s);assert.ok(r);r.visible.combat.done=true;r.visible.combat.winner=win?0:1;r.visible.combat.units.filter(u=>u.side===(win?1:0)).forEach(u=>u.hp=0);return r;}
test('a new league starts at level one, zero gold and one baby per tamer',()=>{const s=E.newGame(41);for(const p of s.players){assert.equal(p.level,1);assert.equal(p.xp,0);assert.equal(p.gold,0);assert.equal(E.all(p).length,1);assert.equal(p.board.filter(Boolean).length,1);assert.equal(D.units[p.board[3].id].cost,1);}assert.equal(s.players[0].board[3].id,'koromon');assert.deepEqual(E.audit(s),[]);});
test('legend selection is cosmetic state and locks during battle',()=>{const s=E.newGame(41);assert.equal(s.legend.id,'bitmon');assert.equal(E.setLegend(s,'tokomon'),true);assert.equal(s.legend.id,'tokomon');assert.equal(E.setLegend(s,'missing'),false);s.phase='battle';assert.equal(E.setLegend(s,'koromon'),false);assert.equal(s.legend.id,'tokomon');});
test('solo difficulty scales only the human opponent and locks during battle',()=>{const make=id=>{const s=E.newGame(81);s.round=4;s.pairs=[[0,1,false]];assert.equal(E.setDifficulty(s,id),true);const r=E.startRound(s);return {s,enemy:r.visible.combat.units.find(u=>u.side===1)};},easy=make('easy'),normal=make('normal'),hard=make('hard');assert.equal(easy.s.difficulty,'easy');assert.equal(hard.s.difficulty,'hard');assert.ok(easy.enemy.max<normal.enemy.max);assert.ok(hard.enemy.max>normal.enemy.max);assert.ok(Math.abs(easy.enemy.max/normal.enemy.max-.88)<1e-9);assert.ok(Math.abs(hard.enemy.atk/normal.enemy.atk-1.12)<1e-9);assert.equal(E.setDifficulty(hard.s,'easy'),false);assert.equal(E.setDifficulty(E.newGame(2),'unknown'),false);});
test('TFT-style XP curve grants two XP per combat and carries overflow',()=>{assert.deepEqual(Object.fromEntries(Object.entries(D.xp)),{'1':2,'2':2,'3':6,'4':10,'5':20,'6':36,'7':60,'8':68});const s=E.newGame(42),p=s.players[0];E.finishRound(s,battle(s));assert.equal(p.level,2);assert.equal(p.xp,0);E.finishRound(s,battle(s));assert.equal(p.level,3);assert.equal(p.xp,0);p.level=3;p.xp=5;E.addXp(p,4);assert.equal(p.level,4);assert.equal(p.xp,3);});
test('every stage follows the requested schedule through 8-7',()=>{assert.deepEqual([1,2,3].map(n=>E.roundInfo(n).type),['creep','creep','creep']);for(let stage=2;stage<=8;stage++){const start=4+(stage-2)*7;assert.deepEqual(Array.from({length:7},(_,i)=>E.roundInfo(start+i).type),['pvp','pvp','pvp','carousel','pvp','pvp','creep']);assert.equal(E.roundInfo(start+6).label,`${stage}-7`);}assert.equal(E.roundInfo(52).label,'8-7');});
test('creep encounters use the story villain roster',()=>{const s=E.newGame(9),expected=[['kuwagamon'],['kuwagamon','shellmon'],['devimon','shellmon']];for(let round=1;round<=3;round++){s.round=round;assert.deepEqual([...new Set(E.creepTeam(s).board.filter(Boolean).map(u=>u.id))].sort(),expected[round-1].sort());}const bosses=['devimon','etemon','vamdemon','piemon','apocalymon'];for(let stage=2;stage<=6;stage++){s.round=4+(stage-2)*7+6;assert.ok(E.creepTeam(s).board.filter(Boolean).every(u=>bosses.includes(u.id)));}});
test('every villain has a valid dedicated GIF sprite',()=>{for(const creep of Object.values(D.creeps)){const file=path.join(__dirname,'../assets',creep.sprite+'.gif');assert.ok(fs.existsSync(file),creep.name);assert.match(fs.readFileSync(file).subarray(0,6).toString(),/^GIF8/);}});
test('creep orbs wait for the legend, preserve PvP streaks and pay only on collection',()=>{const s=E.newGame(18),p=s.players[0];p.last='loss';p.streak=3;const r=battle(s);assert.equal(E.finishRound(s,r),true);assert.equal(p.last,'loss');assert.equal(p.streak,3);assert.equal(p.wins,0);assert.equal(p.inventory.length,0);assert.ok(s.pendingLoot.length>=1);assert.equal(s.lastResult.drops.length,s.pendingLoot.length);const gold=p.gold,orb=s.pendingLoot[0];assert.ok(E.collectLoot(s,orb.id));assert.equal(s.pendingLoot.length,s.lastResult.drops.length-1);assert.ok(p.gold>gold||p.inventory.length||E.all(p).length>1);assert.equal(E.collectLoot(s,orb.id),null);assert.equal(s.income.win,0);assert.deepEqual(E.audit(s),[]);});
test('defeating no creeps grants no loot; PvP never generates equipment',()=>{const s=E.newGame(20),p=s.players[0];E.finishRound(s,battle(s,false));assert.deepEqual(p.inventory,[]);assert.deepEqual(s.lastResult.drops,[]);s.round=4;s.pairs=null;const before=p.inventory.length;E.finishRound(s,battle(s));assert.equal(p.inventory.length,before);assert.equal(s.reward,null);assert.equal(s.lastResult.type,'pvp');assert.equal(p.wins,1);assert.equal(s.income.win,1);});
test('carousel save reload grants one bundle and advances without combat income',()=>{let s=E.newGame(32);s.round=7;E.prepareRound(s);assert.equal(E.startRound(s),null);assert.equal(s.reward.type,'carousel');const offers=JSON.stringify(s.reward);E.prepareRound(s);assert.equal(JSON.stringify(s.reward),offers);s=JSON.parse(JSON.stringify(s));const p=s.players[0],xp=p.xp,gold=p.gold,option=s.reward.options[0];assert.equal(E.chooseReward(s,0),true);assert.equal(E.roundInfo(s).label,'2-5');assert.equal(p.xp,xp);assert.equal(p.gold,gold);assert.ok(p.inventory.includes(option.item));assert.ok(E.all(p).some(u=>u.id===option.unit));assert.equal(E.chooseReward(s,0),false);assert.deepEqual(E.audit(s),[]);});
test('full bench carousel converts unit into gold without losing equipment or stock',()=>{const s=E.newGame(22),p=s.players[0];s.round=7;E.prepareRound(s);const option=s.reward.options[0];for(let i=0;i<9;i++){s.pool.koromon--;p.bench[i]=E.createUnit(s,'koromon');}const gold=p.gold;assert.equal(E.chooseReward(s,0),true);assert.equal(p.gold,gold+D.units[option.unit].cost);assert.ok(p.inventory.includes(option.item));assert.equal(p.bench.length,9);assert.deepEqual(E.audit(s),[]);});
test('AI preparation cannot create items and PvP damage increases each stage',()=>{const s=E.newGame(25),p=s.players[1];s.round=4;E.aiTurn(s,p);assert.equal(p.inventory.length+E.all(p).reduce((n,u)=>n+u.items.length,0),0);let previous=0;for(let stage=2;stage<=8;stage++){const damage=E.stageDamage(stage,3);assert.ok(damage>previous);previous=damage;}});
